- name: enable_docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: restart_docker
  systemd:
    daemon_reload: yes
    name: docker
    state: restarted

- name: restart_kubelet
  systemd:
    daemon_reload: yes
    name: kubelet
    state: restarted
