- name: Add google apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add kubernetes repository
  apt_repository:
    filename: kubernetes
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main

- name: Install kubectl
  apt:
    name: kubectl

- name: Install KVM2 drivers # https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm2-driver
  apt:
    name: ["libvirt-clients", "libvirt-daemon-system", "qemu-kvm"]

- name: Enable libvrtd service
  systemd:
    name: libvirtd
    enabled: yes
    state: started

- name: Create libvirt group
  group:
    name: libvirt

- name: Add user to the libvirt and kvm group
  user:
    name: robin
    groups:
      - libvirt
      - kvm
    append: yes

- name: Install docker machine
  get_url:
    url: https://github.com/docker/machine/releases/download/v0.16.1/docker-machine-Linux-x86_64
    dest: /usr/local/bin/docker-machine
    checksum: sha256:44a008c14549156222b314b1448c22ef255b446419fcf96570f3f288dff318a9
    mode: 0755

- name: Install the docker-machine driver for kvm2
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2
    dest: /usr/local/bin/
    mode: 0755

- name: Install minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/v1.2.0/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    checksum: sha256:123fc9f5656333fb2927cf91666a91cd5b28ef97503418ac2a90a2109e518ed9
    mode: 0755

- name: Use KVM2 as default driver
  become_user: robin
  shell: minikube config set vm-driver kvm2
  notify:
    - minikube_delete

- meta: flush_handlers

- name: Start minikube
  become_user: robin
  shell: minikube start --vm-driver=kvm2
